# Generated by Django 3.1.6 on 2022-07-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
